[package]
name = "regui-nwg"
version = "0.1.0"
edition = "2021"

[dependencies]
regui = { version = "0.1.0", path = "../.." }
native-windows-gui = "1.0.13"

[dev-dependencies]
pollster = "0.3.0"
wgpu = "0.16.1"
#native-windows-derive = "1.0.5"