[package]
name = "iui_raw"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libui-ffi = "0.2.0"
raw-window-handle = "0.5.2"
regui = { version = "0.1.0", path = "../.." }
#wgpu = "0.17.0"
